### ISSUE TITLE
delete stocker , how will the foups in it operate? 

### ISSUE THREAD

**Issue by zhangjiyuan** [tornadocean/SyAutoH#19]
there are some foups in the stocker ,when the stocker is deleted ,do the foups in it should be delete too? Or just reserve them ,when the stocker of same ID compares with the deleted stocker added , the foups in the deleted stocker will be displayed in the new added stocker?

**Comment by SidneyGG** [comment]
Set foups disable in MCS, when the stocker is offline.

**Comment by tornadocean** [comment]
> Set foups disable in MCS, when the stocker is offline.

donot delete the foups, but leave the foups status to disable. when the same stocker is onlined, set the same foups to enable. @MaxinMicrocyber @SidneyGG

**Comment by tornadocean** [comment]
We will use db to manage the foups in mcs. The virtual stockers only manage the foups self.
